behaviors:
  RPG1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 1000
    summary_freq: 100000
    threaded: true
environment_parameters:
  increasement:
    curriculum:
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: RPG1
          signal_smoothing: true
          min_lesson_length: 100
          threshold: -12
        value:
          sampler_type: uniform
          sampler_parameters: 
            min_value: 0.1
            max_value: 0.2
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: RPG1
          signal_smoothing: true
          min_lesson_length: 100
          threshold: -8
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.3
            max_value: 0.4
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: RPG1
          signal_smoothing: true
          min_lesson_length: 100
          threshold: -6
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.5
            max_value: 0.6
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: RPG1
          signal_smoothing: true
          min_lesson_length: 100
          threshold: -4.5
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.7
            max_value: 0.8
      - name: Lesson5
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.9
            max_value: 1.0
  decreasement:
    curriculum:
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: RPG1
          signal_smoothing: true
          min_lesson_length: 100
          threshold: -12
        value: 3
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: RPG1
          signal_smoothing: true
          min_lesson_length: 100
          threshold: -8
        value: 2.5
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: RPG1
          signal_smoothing: true
          min_lesson_length: 100
          threshold: -6
        value: 2
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: RPG1
          signal_smoothing: true
          min_lesson_length: 100
          threshold: -4.5
        value: 1.5
      - name: Lesson5
        value: 1
         
